language: ruby
rvm:
- 2.3.3

deploy:
  provider: pages
  skip_cleanup: true
  github_token: '929b4b1fe9192813ac13175ae1797259e43c61b2' # Set in travis-ci.org dashboard
  on:
    branch: master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
