language: ruby
rvm:
- 2.3.3

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 'f07c073d0cc628252485c9cdd30775d49fee4196' # Set in travis-ci.org dashboard
  on:
    branch: master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
